### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by serkor1** [NumEconCopenhagen/IntroProg-exercises#2]
https://github.com/NumEconCopenhagen/IntroProg-exercises/blob/58313b8cc823414eb8a101876f66f69a0f74ee8a/PS0/problem%20set%200.lyx#L602-L605

Gives a `syntax`-error. Should be,

```tex
 \begin_layout Plain Layout 
 	print('just right') 
 \end_layout
```

**Comment by AskerNC** [comment]
Thank you very much for me aware
I've updated the problem set now
