### ISSUE TITLE
Persistent error in PS3

### ISSUE THREAD

**Issue by serkor1** [NumEconCopenhagen/IntroProg-exercises#4]
## In the jupyter notebook

https://github.com/NumEconCopenhagen/IntroProg-exercises/blob/93a6867cdbf82aefff3a0683f8a7fc1e6f302e19/PS3/problem_set_3.ipynb#L310-L338

## In the solution

https://github.com/NumEconCopenhagen/IntroProg-exercises/blob/93a6867cdbf82aefff3a0683f8a7fc1e6f302e19/PS3/A10.py#L1-L19

----

Even if you copy the defined `functions` in the `A10.py`-program, the `notebook` will throw an `error` - if you run the code as follows,

### Code
```py
def assets_row_by_row(x,R,Y):
    return R*(x['inc']-x['con'])+Y
    
def assets_all_at_once(income,consumption,R,Y):
    return R*(income-consumption)+Y

def assets_adj(assets,R,Y):
    assets *= R
    assets += Y


R = 1.2 # return rate
Y = 1 # income
try:
    dt['assets_1'] = R*(dt['inc']-dt['con'])+Y
    dt['assets_2'] = dt.apply(assets_row_by_row,axis=1,args=(R,Y))
    dt['assets_3'] = assets_all_at_once(dt['inc'].values(),dt['con'].values(),R,Y)
    dt['assets_4'] = dt['inc']-dt['con']
    assets_adj(dt['assets_4'],R,Y)
except Exception as e:
    print(f'An error occurred: {e}')

dt.head()   
```
### Error

```py
An error occurred: 'numpy.ndarray' object is not callable
```

## Why?

The subtle difference lies, I believe, in the use of `df.values` and `df.values()`, the latter uses `numpy` the former is `pandas`-syntax. Is this intended, so we are aware of this difference or is it a bug? 

It took a while to debug, and now I am curious.

**Comment by AskerNC** [comment]
Hi 
This is a good spot, you are absolutely correct. In the notebook `.values` is treated as a method, when it is, in fact, an attribute.
I don't know the original intent, but it feels disingenuous to me, to have a 'hidden' error, when the lines you are supposed to edit are marked. So I've committed a change where `.values` is replaced by `.to_numpy` (which is a method). In most cases `.values`and `.to_numpy` does the same thing, but `.to_numpy` is a bit more explicit.

Thanks for noticing the issue

Best,
Asker
